### ISSUE TITLE
Integration not working with 2026.3

### ISSUE THREAD

**Issue by steiale** [cardouken/homeassistant-unifi-unas#21]
I get multiple errors running 2026.3. I know it is still beta but just as a heads up. Just a few examples… It is related to HA switching to PY 3.14

Logger: custom_components.unifi_unas
Source: custom_components/unifi_unas/__init__.py:374
integration: UniFi UNAS ([documentation](https://github.com/cardouken/homeassistant-unifi-unas/blob/main/README.md), [issues](https://github.com/cardouken/homeassistant-unifi-unas/issues))
First occurred: 07:01:58 (32 occurrences)
Last logged: 07:16:44

SSH connection temporarily unavailable: 'SFTPAttrs' object has no attribute 'size'

Logger: py.warnings
Source: custom_components/unifi_unas/ssh_manager.py:11
integration: UniFi UNAS ([documentation](https://github.com/cardouken/homeassistant-unifi-unas/blob/main/README.md), [issues](https://github.com/cardouken/homeassistant-unifi-unas/issues))
First occurred: 07:01:54 (2 occurrences)
Last logged: 07:01:54

/usr/local/lib/python3.14/site-packages/asyncssh/crypto/cipher.py:29: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0. from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/usr/local/lib/python3.14/site-packages/asyncssh/crypto/cipher.py:30: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0. from cryptography.hazmat.primitives.ciphers.algorithms import TripleDES
